### ISSUE TITLE
context deadline exceeded error when writing from influx to mimir using  influx2cortex proxy

### ISSUE THREAD

**Issue by dhanvsagar** [grafana/influx2cortex#71]
Unable to send data from influx to mimir using influx2cortex proxy (with the configs shows below).

### Telegraf output config

```
[[outputs.http]]
  url = "http://influx2cortex-proxy:8080"
  data_format = "influx"
  timeout = "30s"
  method = "POST"
  interval = "300s"
  flush_interval = "150s"
  insecure_skip_verify = true
  [outputs.http.headers]
    X-Scope-OrgID = "influx-proxy"

```

### Proxy deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx2cortex-proxy
  labels:
    app.kubernetes.io/name: proxy
spec:
  selector:
    matchLabels:
      app: influx2cortex-proxy
  template:
    metadata:
      labels:
        app: influx2cortex-proxy
        app.kubernetes.io/name: proxy
    spec:
      containers:
        - name: influx2cortex
          image: 'influx2cortex-proxy:8d12d69'
          args:
            - "-auth.enable=false"
            - "-write-endpoint=http://mimir-distributor-headless.mimir.svc.cluster.local:8080/api/v1/push"
            - "-skip-label-validation=true"
            - "-max.request.size.bytes=0"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: http2
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: 200m
              memory: 512Mi
```
### Proxy Service
```
apiVersion: v1
kind: Service
metadata:
  name: influx2cortex-proxy
  labels:
    app: influx2cortex-proxy
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
    - name: http2
      port: 8081
      protocol: TCP
      targetPort: http2
  selector:
      app.kubernetes.io/name: proxy
```

### Logs and errors
Inlux2cortex proxy image was built using the Dockerfile provided in the official repository using the latest codebase.

No logs are available at the proxy other than 
```
level=info caller=server.go:107 msg="server listening on address" addr=[::]:8000
level=info caller=server.go:127 msg="GRPC server listening on address" addr=[::]:9095
level=info caller=service.go:75 msg="Starting internal http server" addr=0.0.0.0:8081
level=info caller=server.go:166 msg="Starting grpc server" addr=[::]:9095
level=info caller=server.go:155 msg="Starting http server" addr=[::]:8000
```

Telegraf shows the following error message

```
2022-10-10T13:19:14Z E! [agent] Error writing to outputs.http: Post "http://influx2cortex-proxy:8080": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-10-10T13:19:44Z D! [outputs.http] Buffer fullness: 100015 / 10000000 metrics
2022-10-10T13:19:44Z E! [agent] Error writing to outputs.http: Post "http://influx2cortex-proxy:8080": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
When I tried changing the port number in telegraf output config from 8080 to 8081, shows an error as shown below
```
2022-10-10T13:08:06Z D! [outputs.http] Buffer fullness: 138855 / 10000000 metrics
2022-10-10T13:08:06Z E! [agent] Error writing to outputs.http: when writing to [http://influx2cortex-proxy:8081] received status code: 404
```

Please correct me if my configs are not proper. Also is there any option to enable debug logs in the proxy..?
